### ISSUE TITLE
Client generates text shape events with unset 'calcedFontSize'

### ISSUE THREAD

**Issue by jezhus** [bigbluebutton/bigbluebutton#9621]
This error is caused when executing the process of publishing a recording, it only happens with some recordings
this is the log output:
/var/log/bigbluebutton/presentation/publish-f8f554eaed6145d934cb7db501188353555eef28-1589804628384.log
<img width="895" alt="Screen Shot 2020-05-20 at 7 26 05 PM" src="https://user-images.githubusercontent.com/7368641/82510257-c14a4800-9acf-11ea-83f1-65dd05372a31.png">

When I check the events.xml file I can see that the text field is empty

<img width="703" alt="Screen Shot 2020-05-20 at 7 29 01 PM" src="https://user-images.githubusercontent.com/7368641/82510445-2b62ed00-9ad0-11ea-89bf-f2e2951623f2.png">

BigBlueButton version: 2.2.11

Any ideas how to solve the problem?

**Comment by jesusvaldivia** [comment]
I have this problem with multiple recordings even after upgrading to 2.2.14

**Comment by jesusvaldivia** [comment]
the issue happens when the `calcedFontSize` parameter is undefined
https://github.com/bigbluebutton/bigbluebutton/blob/8938383d67ee01219d68db193d99baeef905cf62/record-and-playback/presentation/scripts/publish/presentation.rb#L633

was solved by adding the following code

```ruby
    calcedFontSize = event.at_xpath('calcedFontSize')
    if !calcedFontSize.nil?
      shape[:calced_font_size] = calcedFontSize.text.to_f
    else
      shape[:calced_font_size] = 0.0
    end
```

**Comment by kepstin** [comment]
I've made a PR that works around this issue on the recording side, but the underlying issue is in the HTML5 client itself - it should not be generating text events where the "calced font size" is not set.

**Comment by kepstin** [comment]
The code in https://github.com/bigbluebutton/bigbluebutton/blob/d11f9e22a0629b49b744a3458fc769ad0e6c8449/record-and-playback/core/scripts/archive/archive.rb#L216-L232 should probably all be removed; the archive script doesn't have permission to remove most of those files, i think, and there's already cleanup provided in a cron job for all those media files.

**Comment by nigel447** [comment]
I have this with a clean bbb version 2.5 and 2.6, in this case the same class of error `undefined method text for nil:NilClass` but generated is a slightly different way  

log /var/log/bigbluebutton/presentation
```
E, [2022-07-15T12:09:42.578757 #11592] ERROR -- : undefined method `text' for nil:NilClass
E, [2022-07-15T12:09:42.578782 #11592] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:835:in `block in process_presentation'
E, [2022-07-15T12:09:42.578791 #11592] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
E, [2022-07-15T12:09:42.578799 #11592] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
E, [2022-07-15T12:09:42.578807 #11592] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
E, [2022-07-15T12:09:42.578814 #11592] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:812:in `process_presentation'
```
in this case error starts here with xml node with eventname **ResizeAndMoveSlideEvent** in the generated /var/bigbluebutton/recording/process/presentation/events.xml

```
  <event timestamp="3479790" module="PRESENTATION" eventname="**ResizeAndMoveSlideEvent**">
    <id>ead068f42ca09a04e7a17c3c3f5ea7bfad9029f3-1657886922826/1</id>
    <date>2022-07-15T12:08:50.356Z</date>
    <yCamera>0.0</yCamera>
    <zoom>0.717929292929293</zoom>
    <timestampUTC>1657886930356</timestampUTC>
    <xCamera>0.0</xCamera>
    <presentationName>ead068f42ca09a04e7a17c3c3f5ea7bfad9029f3-1657886922826</presentationName>
    <podId>DEFAULT_PRESENTATION_POD</podId>
  </event>
```

related ruby code in https://github.com/bigbluebutton/bigbluebutton/blob/develop/record-and-playback/presentation/scripts/publish/presentation.rb
def process_presentation line 900  reads above events.xml then line 923
```
    when 'ResizeAndMoveSlideEvent'
      current_x_offset = event.at_xpath('xOffset').text.to_f
      current_y_offset = event.at_xpath('yOffset').text.to_f
      current_width_ratio = event.at_xpath('widthRatio').text.to_f
      current_height_ratio = event.at_xpath('heightRatio').text.to_f
      panzoom_changed = true
```
we can see the xOffset ect will give the 'undefined method `text' for nil:NilClass' error

**Comment by antobinary** [comment]
I believe this is no longer present on BBB, 2.6.0+ (change of whiteboard, lots of changes in both messaging and recording). No recent encounters. Please open a new issue if you see this on 2.6.0+ (and reference this one)
