### ISSUE TITLE
Setting camera profiles prevent starting of frontend

### ISSUE THREAD

**Issue by aruhri** [bigbluebutton/bigbluebutton#19276]
**Describe the bug**
When you set camera-profiles to reduce bandwidth as described at 
https://docs.bigbluebutton.org/administration/customize/#reduce-bandwidth-for-webcams
BBB-Frontend will not start correctly and shows only a dark blue screen.
It worked in 2.5. Upgrading to 2.7 broke my working setup.
In the js-console of the browser appears an error: `Uncaught TypeError: h.filter is not a function`

**To Reproduce**
1. set camera-profiles as described at https://docs.bigbluebutton.org/administration/customize/#reduce-bandwidth-for-webcams
2. try to start Session (from Greenlight)
3. See the dark blue screen
4. Open console and see the errormessage

**Expected behavior**
Get a working BBB_interface

**Actual behavior**
UI for session does not start. Screen remains dark-blue

**Screenshots**
![console](https://github.com/bigbluebutton/bigbluebutton/assets/9287488/f1678d5c-4e1c-42fa-810a-1e87fb235c6c)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Chrome, Firefox
 - Version 119, 120

**additional context**
The behavior (or similar) was described at 
* https://groups.google.com/g/bigbluebutton-dev/c/fXJDgv6_tkU and
* https://groups.google.com/g/bigbluebutton-setup/c/oVgFkDem6R8/m/KL4OkNEeBgAJ 

but I didn't find an issue here.

**Comment by antobinary** [comment]
I believe this was resolved in BBB 2.7 (not finding the commit though). Now on 3.0 and I can't reproduce. Closing.
