### ISSUE TITLE
Rebuild not working in 2.3a

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#10244]
**Describe the bug**
My 2.3a server does not finish archiving record by bbb-record --rebuild. 

**To Reproduce**
1. You record a meeting.
2. You confirm the meeting is published
3. do bbb-record --rebuild
4. It stops at archiving step, never publish the record. 

**Expected behavior**
Rebuild should be done.

**Additional context**
Posted at https://groups.google.com/forum/#!topic/bigbluebutton-dev/5eQWg98I53U 
The syslog reads
events_archiver.rb:232:in `strip_control_chars': undefined method `tr' for nil:NilClass
I am not sure if this is specific to my server, but if not, it appears to be a bug.

**Comment by paulraper** [comment]
The rebuild function is still not working.

**Comment by aogilvie** [comment]
Dup https://github.com/bigbluebutton/bigbluebutton/issues/9491
