### ISSUE TITLE
Desktop sharing not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/bigbluebutton#4405]
Having openjdk version "1.8.0_131"

Started the desktop sharing on Firefox (it doesn't really matter),
Downloaded the jnlp file
Run it manually through the console with:
> javaws screenshare.jnlp

In the console I got:
> Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

Full log
`Setting up grabber for linux.
input::0.0+0,0 videoSize:5110x1430
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:471)
	at org.bytedeco.javacpp.Loader.load(Loader.java:413)
	at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
	at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:118)
	at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:95)
	at org.bigbluebutton.screenshare.client.javacv.FfmpegScreenshare.setupLinuxRecorder(FfmpegScreenshare.java:322)
	at org.bigbluebutton.screenshare.client.javacv.FfmpegScreenshare.go(FfmpegScreenshare.java:93)
	at org.bigbluebutton.screenshare.client.ScreenSharerRunner.startSharing(ScreenSharerRunner.java:61)
	at org.bigbluebutton.screenshare.client.ScreenRegionSharer$CaptureRegionListenerImp.onStartCapture(ScreenRegionSharer.java:152)
	at org.bigbluebutton.screenshare.client.frame.CaptureRegionFrame.startCapture(CaptureRegionFrame.java:171)
	at org.bigbluebutton.screenshare.client.frame.CaptureRegionFrame.start(CaptureRegionFrame.java:78)
	at org.bigbluebutton.screenshare.client.ScreenRegionSharer.start(ScreenRegionSharer.java:73)
	at org.bigbluebutton.screenshare.client.ScreenRegionSharer.networkConnectionException(ScreenRegionSharer.java:122)
	at org.bigbluebutton.screenshare.client.net.NetworkStreamSender.notifyNetworkConnectionListener(NetworkStreamSender.java:54)
	at org.bigbluebutton.screenshare.client.net.NetworkStreamSender.networkException(NetworkStreamSender.java:104)
	at org.bigbluebutton.screenshare.client.net.NetworkHttpStreamSender.notifyNetworkStreamListener(NetworkHttpStreamSender.java:68)
	at org.bigbluebutton.screenshare.client.net.NetworkHttpStreamSender.sendUpdateMessage(NetworkHttpStreamSender.java:240)
	at org.bigbluebutton.screenshare.client.net.NetworkHttpStreamSender.sendMessageToServer(NetworkHttpStreamSender.java:103)
	at org.bigbluebutton.screenshare.client.net.NetworkHttpStreamSender.access$200(NetworkHttpStreamSender.java:36)
	at org.bigbluebutton.screenshare.client.net.NetworkHttpStreamSender$1.run(NetworkHttpStreamSender.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).

**Comment by jakehell** [comment]
@ffdixon is there a workaround besides moving to html5 client? I am using software created by a company that uses big blue button, and I am getting the same issue. 

I'm not sure if they are able to switch to an html5 client, and would like to know if there is something the end user can do.
